export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const FETCH_DEPARTMENTS_SUCCEEDED = "FETCH_DEPARTMENTS_SUCCEEDED";
export const FETCH_DEPARTMENTS_FAILED = "FETCH_DEPARTMENTS_FAILED";

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCEEDED = "ADD_DEPARTMENT_SUCCEEDED";
export const ADD_DEPARTMENT_FAILED = "ADD_DEPARTMENT_FAILED";

export const FETCH_EMPLOYEES = "FETCH_EMPLOYEES";
export const FETCH_EMPLOYEES_SUCCEEDED = "FETCH_EMPLOYEES_SUCCEEDED";
export const FETCH_EMPLOYEES_FAILED = "FETCH_EMPLOYEES_FAILED";